from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('disciplines/', views.get_disciplines, name='get_disciplines'),
    path('tournaments/', views.get_tournaments, name='get_tournaments'),
    path('tournaments/create/', views.create_tournament, name='create_tournament'),
    path('teams/', views.get_teams, name='get_teams'),
    path('teams/create/', views.create_team, name='create_team'),
    path('participants/', views.get_participants, name='get_participants'),
    path('participants/create/', views.create_participant, name='create_participant'),
    path('matches/', views.get_matches, name='get_matches'),
    path('matches/generate/', views.generate_matches, name='generate_matches'),
    path('matches/<int:match_id>/update/', views.update_match, name='update_match'),    
    path('logout/', views.logout, name='logout'),
    path('logs/', views.get_logs, name='get_logs'),
    path('administrators/create/', views.create_administrator, name='create_administrator'),
    path('tournaments/<int:tournament_id>/start-phase/', views.start_phase, name='start_phase'),
    path('tournaments/<int:tournament_id>/phases/', views.get_phases, name='get_phases'),
    path('phase-matches/<int:match_id>/update/', views.update_phase_match, name='update_phase_match'),
    path('tournaments/<int:tournament_id>/finish/', views.finish_tournament, name='finish_tournament'),
    path('tournaments/<int:tournament_id>/delete/', views.delete_tournament, name='delete_tournament'),
    path('teams/<int:team_id>/delete/', views.delete_team, name='delete_team'),
    path('participants/<int:participant_id>/delete/', views.delete_participant, name='delete_participant'),
    path('matches/<int:match_id>/delete/', views.delete_match, name='delete_match'),
    path('administrators/<int:admin_id>/delete/', views.delete_administrator, name='delete_administrator'),
    path('teams/<int:team_id>/update/', views.update_team, name='update_team'),
    path('participants/<int:participant_id>/update/', views.update_participant, name='update_participant'),
]